### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by noel2004** [noel2004/fabric#1]
###难度：&#9733;

peerex应当允许输出log到文件，client.go的InitGlobal函数中已经给出部分实现，然而，我们需要完成一个logging.Log界面，以便能及时地调用输出io.writer的flush和sync方法将日志同步到文件

日志输出到文件应当实现：
* 对Debug等级的日志不执行任何同步
* 对Warning（含）以下等级的日志调用bufio.writer的flush方法同步到底层io
* 对Erro（含）及以上的日志调用bufio.writer的flush和底层文件的sync方法

peerex还应当将grpc的日志输出至同一文件

**Comment by qzhongwood** [comment]
实现方案
-     对Debug等级的日志不执行任何同步
-     对Warning（含）以下等级的日志调用bufio.writer的flush方法同步到底层io
-     对Erro（含）及以上的日志调用bufio.writer的flush和底层文件的sync方法
-     在core.yaml中增加一个配置：logging.outputfile，用来指定输出log文件的路径，比如/tmp/peer.log

**Comment by noel2004** [comment]
配置改为logging.output.file，并且允许使用logging.output.postfix在给定文件名后追加时间戳后缀

ship it after some changes
