### ISSUE TITLE
"Integrated" chaincode

### ISSUE THREAD

**Issue by noel2004** [noel2004/fabric#2]
### 起因
在fabric 0.6中，chaincode和peer进程分离并之间通过rpc调用通讯。我们希望能发布某种包含部分chaincode和peer的“整合”版本，从而简化一个“全节点”的发布和运行逻辑，并有助于提高系统运行性能

### 实现考虑

* 将原本的rpc调用转换成channel。peer管理一个channel接收进程内chaincode的注册请求并转发到chaincodesupport完成必要的初始化工作，后续的peer - chaincode通讯同样使用channel

* 一个已经注册的chaincode和peer之间必须使用一个独立的channel进行通讯而不能和其它chaincode复用相同的channel，否则chaincode间的互调用可能导致死锁

* 定义一种新的chaincode模式（在core.yaml的chaincode.mode字段中表示）为net_or_dev，当peer发现同名的chaincode已经注册时，不会尝试启动一个新的chaincode进程

* peer选择合适的时机启动内部整合的chaincode模块，这通常在peer/node/start.go的serve函数末尾。

* 配置文件中应当包含选项以关闭特定整合模块的加载，转换至正常的net模式的工作流程

**Comment by qzhongwood** [comment]
与@noel2004 讨论后，调整方案如下：
- peer 和 被整合的chaincode 用回环地址上通信（不用channel通信), 如此改动较少
- 在core.yaml里增加一个chaincode.mode配置 : native.   #native: the chaincode source code is built in with peer process and runs on peer starting up
- 每个native chaincode运行在单独的goroutine里
- 每个native chaincode代码放在 github.com/hyperledger/fabric/peer/chaincode/native/go/$chaincodeName 目录里
- 每个native chaincode 的package名必须和其$chaincodeName 一致

**Comment by noel2004** [comment]
进一步的考虑，将所有要嵌入的chaincode信息和peer项目耦合对二次开发者而言是不便的。更好的方案应当是允许开发者简单地构建一个自己的peer，其中可以加载任意的chaincode

由于peer node start的全部流程实际上被封装在一个函数当中，再加上之前的peerex的实现，我们现在可以简单地做到这一点。仅需在start流程中加入一个可自定义行为的点

另一方面，我们发现fabric已经实现的system_chaincode已经提供了绝大部分的实现可以满足我们的需求，因此我们将实现转为基于system_chaincode
