### ISSUE TITLE
Peer can distinguish nvp and vp and send transaction to later

### ISSUE THREAD

**Issue by noel2004** [noel2004/fabric#3]
### 起因

在当前的nvp实现中，事务被任意地发送到另一个连接的节点，这将带来极大的效率问题。并由于消息环路导致在包含多个nvp的网络中产生消息风暴

改进实现使nvp优先将事务发送到vp可以缓解此问题。但是对复数个没有连接到至少一个vp的nvp而言仍然存在极长的消息传递链路和消息风暴的可能性。幸运的是当前网络拓扑下这一情况应当较为罕见。

### 实现考虑

* 通过约定命名规则，节点的角色可以从HELLO消息的pkid中导出（vp的pkid具有前缀“vp”而nvp的pkid具有前缀"nvp“，peer仅需要在p2p节点列表中保存每个节点的标识即可

* 修改事务执行方法（core/peer/peer.go的ExecuteTransaction）优先选择vp节点作为发送目标；作为一个临时性的方案，应当加入一个开关允许在没有发送到vp节点时返回错误而不是继续选择nvp节点。

* 作为根本的解决手段，pb.Transaction的定义应当被扩展，加入转发次数的计数。或者一个新的包含转发计数的rpc方法（如ProcessTransactionEx）被加入PeerClient，仅后者被允许发送到另一个nvp节点

**Comment by fuyingang** [comment]
节点的配置文件中的peer.validator.enabled这个属性可以把VP和NVP节点区分出来。

**Comment by noel2004** [comment]
这完全是两回事：peer.validator.enabled是指定节点以VP或者NVP的角色运行。issue要解决的问题是节点需要识别**与其连接的其它节点**的角色是VP还是NVP

**Comment by fuyingang** [comment]
嗯，嗯，又看了描述，是这样的。
