### ISSUE TITLE
Auditor peer

### ISSUE THREAD

**Issue by noel2004** [noel2004/fabric#4]
### 起因

需要实现在一致性协议中learner的角色，从而实现一个扩展的nvp节点，此类节点可以读取和验证（执行）整个区块历史，并允许在节点内完成对世界状况的查询。

### 实现考虑

* 实现一个新的consensus模块，参考PBFT的实现，但仅仅同步生成的区块信息，而不参与PBFT的确认的过程

* 此模块允许指定取得确认的vp节点的数量

* 应当扩展noops模块，允许noops向其它节点发送区块数据，因此，扩展的nvp节点既可以和PBFT也可以和noops的vp节点协同工作

* [最终，这一实现和[整合的chaincode功能](2)结合，可以为区块链应用提供一个“准完整”的节点实现]

**Comment by qzhongwood** [comment]
根据上文实现考虑给出实现细节：
1. 增加一种peer类型， learner validate peer（lvp,for short）
2. lvp允许指定取得确认的vp节点的数量
3. 在noops共识模式中, lvp 和 vp 无任何区别:
    - 都会给其他lvp和vp发送consensus消息并且在本地db更新账本，
    - 都会给nvp发送<SYNC_BLOCK_ADDED>消息
4. 在pdft模式中：
    - N(vp的个数)和f(faulty vp(s) we tolerate)不包含lvp的个数
    - lvp会收到所有vp发来的preprepare，prepare和commit三种消息，2f+1个commit消息到达就可以确认一个tx，并且在本地db更新账本确认该tx完成
    - lvp不给任何peer(包括nvp,lvp和vp)发送consensus消息

**Comment by noel2004** [comment]
经过考虑，我们需要在一个更好地设计的框架下实现此功能。因此终止此issue
